spring:
  application:
    name: gateway-service
  cloud:
    config:
      discovery:
        serviceId: config-server
        enabled: true
    gateway:
      routes:
        - id: checkout-service
          uri: lb://checkout-service
          predicates:
          - Path=/checkout
          filters:
            - AddRequestHeader=X-Request-from, gateway
            - AddResponseHeader=X-Response-Red, Blue
        - id: products-service
          uri: lb://product-service
          predicates:
          -Path=/products

server:
  port: 8084
